server:
  port: 9070
spring:
  application:
    name: request-set
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.211.55.3:3306/reqp_set?useSSL=true
    password: hand1234
    username: root
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true